In [ ]:
import numpy as np

In [ ]:
# define Q table
rows = 5
cols = 5
actions = 4

Q_table = np.zeros((rows,cols,actions))

In [ ]:
Q_table

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
actions = ['up','down','left','right']

In [ ]:
rewards = np.full((rows,cols),-1)

In [ ]:
rewards[0,2] = 1
rewards[1,1] = -50
rewards[3,2] = -50
rewards[0,1] = -50
rewards[4,2] = -50
rewards[4,3] = -50
rewards[0,3] = -50
rewards[0,4] = -50
print(rewards)

[[ -1 -50   1 -50 -50]
 [ -1 -50  -1  -1  -1]
 [ -1  -1  -1  -1  -1]
 [ -1  -1 -50  -1  -1]
 [ -1  -1 -50 -50  -1]]


In [ ]:
# start_location()

(0, 0)

In [ ]:
np.random.randint(3)

0

In [ ]:
def is_terminal_state(row,col):
  if rewards[row,col] == -1:
    return False
  else:
    return True

In [ ]:
def start_location():
  row_ = np.random.randint(rows)
  col_ = np.random.randint(cols)
  while is_terminal_state(row_,col_):
    row_ = np.random.randint(rows)
    col_ = np.random.randint(cols)
  return row_ , col_

In [ ]:
x,y = start_location()
print(f'start location : {x},{y}')
print(f'Terminal state : {is_terminal_state(x,y)}')

start location : 1,4
Terminal state : False


In [ ]:
# choose action

def action_select(row,col,epsilon):
  row_ = row
  col_ = col
  if np.random.random() < epsilon:
    return np.argmax(Q_table[row_,col_]) # index
  else:
    return np.random.randint(4) # it will return index


In [ ]:
val =action_select(2,2,0.9)
print(val)

0


In [ ]:
actions

['up', 'down', 'left', 'right']

In [ ]:
rewards[2,0]

-1

In [ ]:
def next_location(current_row,current_col,index):
  # row_ , col_ = current_row , current_col
  if actions[index] == 'up' and current_row > 0:
    current_row -= 1
  elif actions[index] == 'down' and rows -2 >= current_row >= 0:
    current_row += 1
  elif actions[index] == 'left' and current_col != 0:
    current_col -= 1
  elif actions[index] == 'right' and  current_col != rows -1:
    current_col += 1

  return current_row , current_col


In [ ]:
rows , cols = next_location(0,2,3)
print(f'next row {rows} , cols : {cols}')

next row 0 , cols : 3


In [ ]:
def shortest_path(row,col):

  if is_terminal_state(row,col):
    return []
  else:
    l = []
    currentR , currentC = row , col
    l.append([currentR , currentC])
    while not is_terminal_state(currentR , currentC):
      action_index = action_select(currentR , currentC,1)
      currentR , currentC = next_location(currentR , currentC , action_index)
      l.append([currentR , currentC])

    return l



In [ ]:
next_location(0,1,0)

(0, 1)

In [ ]:
# training
epsilon = 0.9
discount = 0.9
lr = 0.9

for i in range(1000):
  print(f'Episode : {i}')

  # choosse a starting location
  start_x , start_y = start_location()
  print(f'terminal state : {is_terminal_state(start_x,start_y)} start_x {start_x} start y {start_y} ')
  while not is_terminal_state(start_x,start_y):

    #choose action
    action_index = action_select(start_x,start_y,epsilon)

    # save the old state x,y
    old_row , old_col = start_x, start_y

    # print(f'old row : {old_row} old_col : {old_col}')


    # after selecting action  go to the perform action to go to the next state
    new_x , new_y = next_location(start_x,start_y,action_index)

    # print(f'new row : {new_x} new_col : {new_y}')

    reward = rewards[new_x,new_y]
    old_q_val = Q_table[old_row , old_col,action_index]

    temporal_diff = reward + (discount * np.max(Q_table[new_x,new_y])) - old_q_val
    update = old_q_val + lr * temporal_diff
    print(update)
    Q_table[old_row , old_col,action_index] = update
    start_x , start_y = new_x , new_y

  print('complete')

Episode : 0


ValueError: ignored

In [ ]:
path = shortest_path(0,0)
print(f'shortest path : {path}')
path.reverse()
print(f'Reverse path : {path}')

shortest path : [[0, 0], [1, 0], [2, 0], [2, 1], [2, 2], [1, 2], [0, 2]]
Reverse path : [[0, 2], [1, 2], [2, 2], [2, 1], [2, 0], [1, 0], [0, 0]]


In [ ]:
rewards

array([[ -1, -50,   1, -50, -50],
       [ -1, -50,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  -1],
       [ -1,  -1, -50,  -1,  -1],
       [ -1,  -1, -50, -50,  -1]])

In [ ]:
Q_table

array([[[ -4.12147739,  -3.50461   ,  -4.1502043 , -49.5       ],
        [  0.        ,   0.        ,   0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ]],

       [[ -4.14965949,  -2.7829    ,  -3.50458667, -49.5       ],
        [  0.        ,   0.        ,   0.        ,   0.        ],
        [  1.        ,  -1.09      , -50.        ,  -1.09      ],
        [-50.        ,  -1.98099999,  -0.1       ,  -1.981     ],
        [-49.9999995 ,  -2.78289894,  -1.09      ,  -1.981     ]],

       [[ -3.50460999,  -3.50450597,  -2.7829    ,  -1.981     ],
        [-49.9999995 ,  -2.78289995,  -2.7829    ,  -1.09      ],
        [ -0.1       , -50.        ,  -1.981     ,  -1.981     ],
        [ -1.09      ,  -2.7829    ,  -1.09      ,  -2.78289888],
        [ -1.981     ,  -3.50357697,  -1.981     ,  -2.7829    ]],

    

# DEEP Q LEARNING

In [ ]:
grid_world = np.array([
    [0, 0, 0],
    [0, -1, 0],
    [0, 0, 1]
])

print(grid_world)

[[ 0  0  0]
 [ 0 -1  0]
 [ 0  0  1]]


In [ ]:
import torch

In [ ]:
torch.tensor(grid_world.flat[:])

tensor([ 0,  0,  0,  0, -1,  0,  0,  0,  1])

In [ ]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

# Define the grid world environment
# 0: empty, -1: obstacle, 1: goal
grid_world = np.array([
    [0, 0, 0],
    [0, -1, 0],
    [0, 0, 1]
])

# Define the Q-network
class QNetwork(nn.Module):
    def __init__(self, input_size, output_size):
        super(QNetwork, self).__init__()
        self.fc1 = nn.Linear(input_size, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, output_size)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Hyperparameters
learning_rate = 0.001
gamma = 0.9
epsilon = 0.1
num_episodes = 1000
batch_size = 32

# Initialize Q-network and optimizer
input_size = grid_world.size
output_size = 4  # up, down, left, right
q_network = QNetwork(input_size, output_size)
optimizer = optim.Adam(q_network.parameters(), lr=learning_rate)

# Deep Q-learning algorithm
for episode in range(num_episodes):
    state = 0  # Start state (top-left corner)
    done = False

    while not done:
        q_values = q_network(torch.tensor(grid_world.flat[state], dtype=torch.float32))

        if np.random.rand() < epsilon:  # Exploration
            action = np.random.randint(output_size)
        else:  # Exploitation
            action = torch.argmax(q_values).item()

        next_state = state + (action // 2) * 3  # Calculate the next state based on the action

        if grid_world.flat[next_state] == -1:  # Hit an obstacle
            reward = -1
            next_state = state
        elif grid_world.flat[next_state] == 1:  # Reached the goal
            reward = 1
            done = True
        else:  # Empty cell
            reward = 0

        # Update Q-values using Bellman equation and deep Q-learning
        q_values_next = q_network(torch.tensor(grid_world.flat[next_state], dtype=torch.float32))
        target_q = reward + gamma * torch.max(q_values_next) if not done else reward

        loss = nn.MSELoss()(q_values[action], target_q)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        state = next_state

    if episode % 100 == 0:
        print(f"Episode {episode}: Total reward = {reward}")

# Print the learned Q-network
print("Learned Q-network:")
print(q_network)


RuntimeError: ignored